### PR TITLE
Added angle button for expansion and collision

### LINKED ISSUE #11: Add a chevron indicator for collapsed/expanded sections
See https://developer.microsoft.com/en-us/microsoft-edge/platform/status/beacon/ on the right.

### PR DESCRIPTION
**Pull request by gakshat14**
I have added the button as well as the functionality. Though CSS need to be changed

Fixes #11.

### CODE REVIEW

**Comment by locks** [comment]
Thank you! At the moment I can't check locally, and seems we have a hard-coded path in the code that is making the Netlify deploy break so that's out as well.
I'll check later this week.
@MelSumner if you have some time, 👀 the CSS changes.

**Comment by MelSumner** [comment]
What about the chevrons instead of the angles? The chevrons are bolder and may perhaps be a better fit. Could you include a screenshot too please?

**Comment by locks** [comment]
Hi @gakshat14, do you have some time to address @MelSumner's comments? :)

**Comment by jenweber** [comment]
Hi @gakshat14, thanks for your work on this app. However in order to increase the umbrella of supported browsers, we have now converted statusboard into an Ember app. If you'd like to help out, let me know!

**Pull request closed without merging**
