### PR TITLE
move to a 3:1 column design

### PR DESCRIPTION
**Pull request by locks**
- Align statuses on the left
- Move availability below status so it shows for collapsed sections
- Tweak availability text

statusboad

### CODE REVIEW

**Comment by knownasilya** [comment]
The status looks weird by itself above a header that takes all the focus. Maybe add a "Status" header above the status. This way the styling is similar and the visual flow is better.

**Comment by locks** [comment]
I tried moving the sections to the right column, but unless you're on a very wide screen, it gets hella cramped.

**Comment by knownasilya** [comment]
Even with champions being a vertical list?

**Comment by MelSumner** [comment]
Potential solutions for the contributors design: 

1. put names under the photos
2. make the photos a little smaller, and have them get bigger on hover.

**Pull request merged**
