### PR TITLE
[WIP] Integrate website styles

### PR DESCRIPTION
**Pull request by chancancode**
- Import website "frame" (styles, JS, markup, etc)
- Remove most layout styles and inherit from website
- Tweak styles to fit into website frame

TODO:

- Don't hardcode website assets with digest (those are
  only to aid development, but still)
- Another consistency pass

### CODE REVIEW

**Comment by tomdale** [comment]
Correct me if I'm wrong @locks , but I think the plan was to build this as a Glimmer component that gets embedded into the Ember website? In that case, inlining the Ember frame and styles would cause it to double-render once embedded.

**Comment by locks** [comment]
Confirm, the intent is to use the same strategy as https://emberjs.com/builds/ and https://emberjs.com/dashboard/.

**Comment by chancancode** [comment]
@tomdale @locks yes that's what I assumed also. The built JS/CSS bundles will be included on the host page via a link/script tag, which will then look for a `#content` and render the app in there. The `index.html` (the "frame") in this repo will therefore not be used at all except to aid development in this repo itself (which is why the hardcoding hacks are a little bad but not _so_ bad).

**Comment by locks** [comment]
@chancancode what's WIP about it? I'm for merging this as-is, since it shouldn't impact deployment.

**Comment by chancancode** [comment]
@locks there are more cleanup to do, such as deleting the unused styles and figure out what to do with the hard-coded asset URLs. But yes I think it is probably fine to merge if we are in a hurry.

**Pull request merged**
